### PR TITLE
additional suggestions for unsatisfied features

### PR DESCRIPTION
**Pull request by WhiteRaven777**
I will present the following change proposal.

- fix README.md
  -added the modified README.md to the original repository and defined this state as tag: v1.0.0
- support for Debug log
  - defined this state as tag: v1.1.0
- supported output to syslog by TCP connection
  - defined this state as tag: v1.2.0

Adding the Debug log and supporting TCP transfers solves the pain of using in realistic products.

### CODE REVIEW

**Comment by WhiteRaven777** [comment]
I added the fix code because the bug was identified.

**Comment by lufia** [comment]
I think most of this p-r is good but this has an incompatible change that is to change function signature of NewLogger.

```diff
- func NewLogger(facility Facility, tag string) Logger
+ func NewLogger(f Facility, tag string, debug bool, addr ...string) (Logger, error)
```

Could you keep old signature of NewLogger? For example:

```go
func NewLoggerWithOptions(f Facility, tag string, debug bool, addr ...string) {
    ...
}
func NewLogger(f Facility, tag string) Logger {
    l, err := NewLoggerWithOptions(f, tag, false)
    if err != nil {
        log.Fatal(err) // or might be able to use panic(err)
    }
    return l
}
```

**Comment by WhiteRaven777** [comment]
The reason I changed the return value is based on the interpretation that the error should not be hidden internally and the process itself should not be interrupted.
Ensuring error transparency allows programs using this package to make error-based decisions.

Having an external package decide whether to abort the process reduces the design freedom of the designer using the package.

`func NewLogger` is certainly a public method, but I think its use scope is complete within the package.
Given the above interpretation, I determine that this disruptive change is acceptable, but is there still a problem?

If there is a problem, please suggest a design example that uses this method outside the package.
If you tell me how to use this method effectively outside of the package, I can understand your point.

Thank you.

**Comment by lufia** [comment]
I see.

IMHO. The Go package should not include incompatible change without changing major version, but this package hasn't published with version tag. So I accept this changes.

**Comment by WhiteRaven777** [comment]
thanks for merged.

**Pull request merged**
